### PR TITLE
spinner/pannelcard-loading/switch

### PR DESCRIPTION
**Pull request by RichardX366**
Added Spinner component, added PanelCard loading property, and made ToggleSwitch visible from storybook.

### CODE REVIEW

**Comment by chuxu200328** [comment]
when I set footer or header for panelcard right on story book, there is an error.

**Comment by RichardX366** [comment]
That's because those are meant to be react components.

**Comment by chuxu200328** [comment]
then that type should not be object?

**Review by chuxu200328 — APPROVED** [review]
fix the story book error and ready to merge

**Comment by RichardX366** [comment]
I can't fix, react nodes are interpreted as objects.

**Pull request merged**
